<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Music World</title>
    <link rel="shortcut icon" href="img/favicon.jpg" type="image/x-icon">
    <link rel="stylesheet" href="css/estilos.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">

</head>
<body>
    <header>
        <nav>
            <a href="#">Inicio</a>
            <a href="#">Acerca de</a>
            <a href="#">Portafolio</a>
            <a href="#">Servicios</a>
            <a href="#">Contacto</a>
        </nav>
        <section class="textos-header">
            <h1>Potencia tus ventas, al menos 200%</h1>
            <h2>Con una pagina web potente</h2>
        </section>
        <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->
        <div class="wave"style="height: 150px; overflow: hidden;" ><svg viewBox="0 0 500 150" preserveAspectRatio="none" 
            style="height: 100%; width: 100%;">
            <path d="M0.00,49.98 C166.19,107.06 349.20,-49.98 500.00,49.98 L500.00,150.00 L0.00,150.00 Z" 
            style="stroke: none; fill: rgb(255, 255, 255);"></path>
        </svg></div>
    </header>
    <main>
        <section class="contenedor sobre-nosotros">
            <h2 class="titulo">Nuestro producto</h2>
            <div class="contenedor-sobre-nosotros">
                <img class="image-about-us"src="img/ilustracion2.svg" alt="">
                <div class="contenido-textos">
                    <h3><span>1 </span>Los mejores productos</h3>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis, nemo hic. Ipsa est accusamus aspernatur adipisci autem? Blanditiis asperiores quod hic vitae ut praesentium nobis molestiae autem dignissimos quibusdam! Pariatur.    
                    </p>
                    <br>
                    <h3><span>2 </span>Los mejores productos</h3>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis, nemo hic. Ipsa est accusamus aspernatur adipisci autem? Blanditiis asperiores quod hic vitae ut praesentium nobis molestiae autem dignissimos quibusdam! Pariatur.    
                    </p>
                </div>
            </div>
        </section>
        <section class="portafolio">
            <div class="contenedor">
                <h2 class="titulo">Portafolio</h2>

                <div class="galeria-port">

                    <div class="image-port">
                        <img src="img/img1.jpg" alt="">
                        <div class="hover-gallery">
                            <img src="img/icono1.png" alt="">
                            <p>Nuestro Trabajo</p>
                        </div>
                    </div>

                    <div class="image-port">
                        <img src="img/img2.jpg" alt="">
                        <div class="hover-gallery">
                            <img src="img/icono1.png" alt="">
                            <p>Nuestro Trabajo</p>
                        </div>
                    </div>

                    <div class="image-port">
                        <img src="img/img3.jpg" alt="">
                        <div class="hover-gallery">
                            <img src="img/icono1.png" alt="">
                            <p>Nuestro Trabajo</p>
                        </div>
                    </div>

                    <div class="image-port">
                        <img src="img/img4.jpg" alt="">
                        <div class="hover-gallery">
                            <img src="img/icono1.png" alt="">
                            <p>Nuestro Trabajo</p>
                        </div>
                    </div>
                    <div class="image-port">
                        <img src="img/img5.jpg" alt="">
                        <div class="hover-gallery">
                            <img src="img/icono1.png" alt="">
                            <p>Nuestro Trabajo</p>
                        </div>
                    </div>

                    <div class="image-port">
                        <img src="img/img6.jpg" alt="">
                        <div class="hover-gallery">
                            <img src="img/icono1.png" alt="">
                            <p>Nuestro Trabajo</p>
                        </div>
                    </div>
                    <div class="image-port">
                        <img src="img/img7.jpg" alt="">
                        <div class="hover-gallery">
                            <img src="img/icono1.png" alt="">
                            <p>Nuestro Trabajo</p>
                        </div>
                    </div>

                    <div class="image-port">
                        <img src="img/img8.jpg" alt="">
                        <div class="hover-gallery">
                            <img src="img/icono1.png" alt="">
                            <p>Nuestro Trabajo</p>
                        </div>
                    </div>
                </div>

                

            </div>
        </section>
        <section class="clientes contenedor">
            <h2 class="titulo">Que dicen nuestros clientes</h2>
            <div class="cards">

                <div class="card">
                    <img src="img/dualipa.jpg" alt="">
                    <div class="contenido-texto-card">
                        <h4>Dua Lipa</h4>
                        <p>Lorem ipsum dolor sit amet . Natus consectetur voluptatum qui sint illo praesentium ipsa dolor,cumque blanditiis possimus porro.</p>
                    </div>
                </div>
                
                <div class="card">
                    <img src="img/camila-cabello.jpg" alt="">
                    <div class="contenido-texto-card">
                        <h4>Camila Cabello</h4>
                        <p>Lorem ipsum dolor sit amet . Natus consectetur voluptatum qui sint illo praesentium ipsa dolor,cumque blanditiis possimus porro.</p>
                    </div>
                </div>

            </div>
        </section>
        <section class="about-services">
            <div class="contenedor">                
                <h2 class="titulo">Nuestros servicios</h2>
                <div class="servicio-cont">
                    <div class="servicio-ind">
                        <img src="img/ilustracion1.svg" alt="">
                        <h3>Name</h3>
                        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde, doloremque!</p>
                    </div>

                    <div class="servicio-ind">
                        <img src="img/ilustracion4.svg" alt="">
                        <h3>Name</h3>
                        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde, doloremque!</p>
                    </div>

                    <div class="servicio-ind">
                        <img src="img/ilustracion3.svg" alt="">
                        <h3>Name</h3>
                        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde, doloremque!</p>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <footer>
        <div class="contenedor-footer">
            <div class="content-foo">
                <h4>Email</h4>
                <p>alexunmsm2016@gmail.com</p>
            </div>
            <div class="content-foo">
                <h4>Phone</h4>
                <p>987654312</p>
            </div>
            <div class="content-foo">
                <h4>Location</h4>
                <p>Villa el Salvador</p>
            </div>
        </div>
        <h2 class="titulo-final">&copy; AlexRC Design</h2>
    </footer>
</body>
</html>